---
title: "Untitled"
output: ioslides_presentation
date: '2022-11-29'
---

## Load Packages
```{r, message = FALSE}
library(ggplot2)
library(dplyr)
```

## Raw Data
```{r, cache = TRUE, echo=FALSE}
surveys <- read.csv("../data/REEF_AllSurveyData_FISH274.csv")

surveys %>% 
  select(formid, exp, date, habitat, abundance, geogr) %>% 
  head()
```

## Average Yearly Abundance of Lionfish
```{r}
year_df <- surveys %>%
  group_by(year) %>%
  filter(year >= "2009") %>% 
  summarize(yearly_avg_abundance = mean(abundance))

head(year_df)
```

## Graph Changes in abundance by year  
```{r, message = FALSE}
year_df %>% 
  ggplot(aes(x = year, y = yearly_avg_abundance))+
  geom_point()+ #scatterplot
  theme_bw()+ #make background black and white
  scale_y_log10()+
  labs(title = "Yearly Abundance of Lionfish in the Flordia Keys", x = "Year", 
       y = "Relative Abundance of Lionfish")+
  geom_smooth(method = lm) #insert linear model
```

## Create two data frames to stack them for experience calculations. All results of novice surveyors
```{r}
expN_df <- surveys %>%
  select(year, exp, abundance) %>% 
  filter(exp == "N") %>% 
  group_by(year) %>%
  summarise(yearly_abd = mean(abundance))
```

## All results of expert surveyors
```{r}
expE_df <- surveys %>%
  select(year, exp, abundance) %>% 
  filter(exp == "E")%>% 
  group_by(year) %>%
  summarise(yearly_abd = mean(abundance))
```

## Graph expert vs novice using layers
```{r}
ggplot()+
  geom_point(data = expE_df, aes(x = year, y = yearly_abd), color = "aquamarine3", size = 3)+
  geom_point(data = expN_df, aes(x = year, y = yearly_abd), color = "deeppink", size = 3, alpha = 0.5)+
  scale_y_log10()+
  labs(x = "Year", y= "Abundance", title= "Relative Abundance of Lionfish")+
  theme_bw()
  
```

## Graph abundance based on habitat survey was conducted in
```{r, message=FALSE, warning = FALSE}
test <- surveys %>% 
  group_by(year) %>%
  filter(habitat %in% 1:11) %>% 
  ggplot(aes(x = year, y = abundance))+
  geom_histogram(stat = 'identity') +
  facet_wrap(~HabitatType)+  
  labs(x = "Year", y= "Abundance", title= "Abundance Measures Based on Habitat")
```
  
## Habitat Type Key
```{r, echo = FALSE}
habitat_names <- c("Mixed", "High-Profile Reef", "Low-Profile Reef",
                   "Sloping Dropoff","Wall","Ledge","Grass", "Sand", 
                   "Rubble", "Artificial","Open Water")
habitat_code <- c(1:11)

df <- data.frame(first_column = habitat_code, second_column =habitat_names)

knitr::kable(df, format = "html", align = rep('l', 5), col.names = 
               c("Habitat Code", "Habitat Type"))

```